#ifndef _NET_GENERAL_COMMAND_H_
#define _NET_GENERAL_COMMAND_H_

enum {
	E_NET_GEN_CMD_READ_CABC_PWM_REQ = 1,
	E_NET_GEN_CMD_READ_CABC_PWM_ACK,

	E_NET_GEN_CMD_READ_DISPLAY_ID_NOTIFY,

	E_NET_GEN_CMD_SET_IP_INFO_REQ,
	E_NET_GEN_CMD_SET_MAC_INFO_REQ,

	E_NET_GEN_CMD_DO_FACOTRY_RESET_REQ,

	// Power calibration
	E_NET_GEN_CMD_POWER_CALIBRATION_REQ,
	E_NET_GEN_CMD_POWER_SETING_BURN_REQ,
	
	E_NET_GEN_CMD_START_SCAN_REQ,
	E_NET_GEN_CMD_SCAN_RESULT,

	E_NET_GEN_CMD_CA310_READ_FLICK,
	E_NET_GEN_CMD_CA310_READ_FLICK_RESULT,

	E_NET_GEN_CMD_SET_BOMB_REQ,
	E_NET_GEN_CMD_PAINT_RECTANGLE,
	E_NET_GEN_CMD_NUMS
};
	
#endif

